#
# Copyright (c) 2019, 2021 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
#
apiVersion: v1
name: hono
description: |
  Eclipse Honoâ„¢ provides remote service interfaces for connecting large numbers of IoT devices to a back end and
  interacting with them in a uniform way regardless of the device communication protocol.
version: 1.10.15
# Version of Hono being deployed by the chart
appVersion: 1.10.0
keywords:
  - iot-chart
  - IoT
  - messaging
home: https://www.eclipse.org/hono/
sources:
  - https://github.com/eclipse/hono
icon: https://www.eclipse.org/hono/favicon/favicon-48x48.png
maintainers:
  - name: dejanb
    email: dbosanac@redhat.com
  - name: ctron
    email: jreimann@redhat.com
  - name: sophokles73
    email: kai.hudalla@bosch.io
