{{- $amqpEnabled := and ( has "amqp" .Values.messagingNetworkTypes ) .Values.amqpMessagingNetworkExample.enabled -}}
{{- if $amqpEnabled }}
#
# Copyright (c) 2019, 2022 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
#
apiVersion: v1
kind: Service
metadata:
  {{- $args := dict "dot" . "component" "amqp-messaging-network-router" "name" "dispatch-router-ext" }}
  {{- include "hono.metadata" $args | nindent 2 }}
  {{- with .Values.amqpMessagingNetworkExample.dispatchRouter.svc.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
  - name: amqps
    port: 15671
    protocol: TCP
    targetPort: amqps
    {{- $amqpsArgs := dict "dot" . "port" 30671 }}
    {{- include "hono.nodePort" $amqpsArgs | nindent 4 }}
  {{- if .Values.amqpMessagingNetworkExample.insecurePortEnabled }}
  - name: amqp
    port: 15672
    protocol: TCP
    targetPort: amqp
    {{- $amqpArgs := dict "dot" . "port" 30672 }}
    {{- include "hono.nodePort" $amqpArgs | nindent 4 }}
  {{- end }}
  {{- if .Values.adapters.externalAdaptersEnabled }}
  - name: internal
    port: 15673
    protocol: TCP
    targetPort: internal
    {{- $internalArgs := dict "dot" . "port" 30673 }}
    {{- include "hono.nodePort" $internalArgs | nindent 4 }}
  {{- end }}
  selector:
    {{- include "hono.matchLabels" $args | nindent 4 }}
  {{- include "hono.serviceType" . }}
{{- with .Values.amqpMessagingNetworkExample.dispatchRouter.svc.loadBalancerIP }}
  loadBalancerIP: {{ . | quote }}
{{- end }}
{{- end }}
