apiVersion: v1
kind: Service
metadata:
  name: "{{ include "hawkbit.fullname" . }}-simple-ui-service"
  labels:
    app.kubernetes.io/name: "{{ include "hawkbit.name" . }}-simple-ui"
  {{- with .Values.serviceSimpleUI.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.serviceSimpleUI.type }}
  ports:
    - port: {{ .Values.serviceSimpleUI.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: "{{ include "hawkbit.name" . }}-simple-ui"
    app.kubernetes.io/instance: "{{ .Release.Name }}-simple-ui"
