{{- if .Values.dataGridExample.enabled }}
#
# Copyright (c) 2019, 2020 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
#
apiVersion: apps/v1
kind: StatefulSet
metadata:
  {{- $args := dict "dot" . "component" "data-grid" "name" "data-grid" }}
  {{- include "hono.metadata" $args | nindent 2 }}
spec:
  replicas: 1
  serviceName: {{ printf "%s-%s" .Release.Name $args.name }}
  selector:
    matchLabels:
      {{- include "hono.matchLabels" $args | nindent 6 }}
  template:
    metadata:
      {{- include "hono.metadata" $args | nindent 6 }}
    spec:
      containers:
      - image: {{ .Values.dataGridExample.imageName | quote }}
        imagePullPolicy: IfNotPresent
        name: hono-data-grid
        command:
        - /opt/infinispan/bin/server.sh
        - -c
        - /opt/infinispan/server/conf/hono/hono-data-grid.xml
        env:
        - name: JDK_JAVA_OPTIONS
          value: "-XX:MinRAMPercentage=85 -XX:MaxRAMPercentage=85"
        - name: JAVA_OPTIONS
          value: {{ printf "-Djgroups.dns.query=%s-%s" .Release.Name $args.name }}
        ports:
        - name: hotrod
          containerPort: 11222
          protocol: TCP
        volumeMounts:
        - mountPath: /opt/infinispan/server/conf/hono
          name: conf
          readOnly: true
        livenessProbe:
          httpGet:
            path: /rest/v2/cache-managers/routing-info/health/status
            port: hotrod
          failureThreshold: 5
          initialDelaySeconds: {{ .Values.dataGridExample.livenessProbeInitialDelaySeconds }}
          successThreshold: 1
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /rest/v2/cache-managers/routing-info/health/status
            port: hotrod
          failureThreshold: 5
          initialDelaySeconds: {{ .Values.dataGridExample.readinessProbeInitialDelaySeconds }}
          successThreshold: 1
          timeoutSeconds: 3
        {{- with .Values.dataGridExample.resources }}
        resources:
          {{- . | toYaml | nindent 10 }}
        {{- end }}
        terminationMessagePath: /dev/termination-log
      volumes:
      - name: conf
        configMap:
          name: {{ printf "%s-%s-conf" .Release.Name $args.name }}
{{- end }}
