{{- if .Values.dataGridExample.enabled }}
#
# Copyright (c) 2019, 2021 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
#
apiVersion: apps/v1
kind: StatefulSet
metadata:
  {{- $args := dict "dot" . "component" "data-grid" "name" "data-grid" "componentConfig" .Values.dataGridExample }}
  {{- include "hono.metadata" $args | nindent 2 }}
spec:
  replicas: 1
  serviceName: {{ printf "%s-%s" (include "hono.fullname" .) $args.name }}
  selector:
    matchLabels:
      {{- include "hono.matchLabels" $args | nindent 6 }}
  template:
    metadata:
      {{- include "hono.metadata" $args | nindent 6 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- include "hono.pod.priorityClassName" $args | nindent 6 }}
      {{- include "hono.pod.affinity" $args | nindent 6 }}
      containers:
      - image: {{ .Values.dataGridExample.imageName | quote }}
        imagePullPolicy: IfNotPresent
        name: hono-data-grid
        command:
        - /opt/infinispan/bin/server.sh
        - -c
        - hono-data-grid.xml
        - -Dquarkus.log.category."org.infinispan.AUDIT".level=WARN
        env:
        - name: JDK_JAVA_OPTIONS
          value: "-XX:MinRAMPercentage=85 -XX:MaxRAMPercentage=85"
        - name: JAVA_OPTIONS
          value: {{ printf "-Djgroups.dns.query=%s-%s" (include "hono.fullname" .) $args.name }}
        ports:
        - name: hotrod
          containerPort: 11222
          protocol: TCP
        volumeMounts:
        - mountPath: /opt/infinispan/server/conf/hono-data-grid.xml
          name: conf
          subPath: hono-data-grid.xml
          readOnly: true
        - mountPath: /opt/infinispan/server/conf/users.properties
          name: conf
          subPath: users.properties
          readOnly: true
        - mountPath: /opt/infinispan/server/conf/public-groups.properties
          name: conf
          subPath: public-groups.properties
          readOnly: true
        - mountPath: /opt/infinispan/server/conf/mgmt-groups.properties
          name: conf
          subPath: mgmt-groups.properties
          readOnly: true
        {{- include "hono.component.healthChecks" $args | nindent 8 }}
        {{- with .Values.dataGridExample.resources }}
        resources:
          {{- . | toYaml | nindent 10 }}
        {{- end }}
        terminationMessagePath: /dev/termination-log
      volumes:
      - name: conf
        configMap:
          name: {{ printf "%s-%s-conf" (include "hono.fullname" .) $args.name }}
{{- end }}
