{{- if .Values.adapters.mqtt.enabled }}
#
# Copyright (c) 2019, 2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
#
{{- $args := dict "dot" . "component" "adapter-mqtt" "name" "adapter-mqtt" "componentConfig" .Values.adapters.mqtt }}
apiVersion: apps/v1
kind: Deployment
metadata:
  {{- include "hono.metadata" $args | nindent 2 }}
  {{- include "hono.deploymentAnnotations" $args | indent 2 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "hono.matchLabels" $args | nindent 6 }}
  template:
    metadata:
      {{- include "hono.metadata" $args | nindent 6 }}
      {{- include "hono.podAdditionalLabels" $args | nindent 8 }}
      annotations:
        {{- include "hono.podAnnotations" $args | nindent 8 }}
        {{- include "hono.podAdditionalAnnotations" $args | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- include "hono.pod.priorityClassName" $args | nindent 6 }}
      {{- include "hono.pod.affinity" $args | nindent 6 }}
      serviceAccountName: {{ printf "%s-%s" ( include "hono.fullname" . ) "adapter" | quote }}
      containers:
      {{- include "hono.otel.agent" . | indent 6 }}
      {{- include "hono.container" $args | indent 6 }}
        {{- with $args.componentConfig.cmdLineArgs }}
        args:
        {{- range . }}
        - {{ . | quote }}
        {{- end }}
        {{- end }}
        ports:
        - name: health
          containerPort: {{ include "hono.healthCheckPort" . }}
          protocol: TCP
        - name: mqtt
          containerPort: 1883
          protocol: TCP
        - name: secure-mqtt
          containerPort: 8883
          protocol: TCP
        securityContext:
          privileged: false
        env:
        - name: JDK_JAVA_OPTIONS
          value: {{ .Values.adapters.mqtt.javaOptions | quote }}
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        {{- include "hono.component.frameworkEnv" $args | indent 8 }}
        {{- include "hono.component.envFrom" $args | indent 8 }}
        volumeMounts:
        {{- include "hono.container.volumeMounts" $args | indent 8 }}
        {{- with .Values.adapters.mqtt.resources }}
        resources:
          {{- . | toYaml | nindent 10 }}
        {{- end }}
        {{- include "hono.component.healthChecks" $args | nindent 8 }}
      volumes:
      {{- include "hono.pod.volumes" $args | indent 6 }}
{{- end }}
