# Copyright (c) 2019, 2021 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
---
# Default values for hawkbit.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: "hawkbit/hawkbit-update-server"
  tag: 0.5.0-mysql
  pullPolicy: IfNotPresent

replicaCount: 1

## podDisruptionBudget configuration
podDisruptionBudget:
  enabled: false
  minAvailable: 1

## Pod Security Context
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
securityContext:
  enabled: true
  # 65534 is the uid of user nobody in the docker image
  fsGroup: 65534
  runAsUser: 65534
  extra: {}

## strategy used to replace old Pods by new ones
## ref: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy
updateStrategy:
  ## default is re-create, because of possible database migrations
  type: Recreate

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  annotations: {}
    # traefik.ingress.kubernetes.io/affinity: "true"

livenessProbe:
  initialDelaySeconds: 240
  timeoutSeconds: 5
readinessProbe:
  initialDelaySeconds: 120
  timeoutSeconds: 5

ingress:
  enabled: false
  ingressClassName:
  annotations: {}
    # ingress.kubernetes.io/ssl-redirect: "true"
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: hawkbit.local
      paths: []
  tls: []
  #  - secretName: hawkbit-tls
  #    hosts:
  #      - hawkbit.local

routes:
  enabled: false
  tls: true

# enable local file storage
fileStorage:
  enabled: true
  pvcSize: "1Gi"
  mountPath: "/var/lib/hawkbit-storage"

# env vars for configuration
env:
  springDatasourceHost: "hawkbit-mysql"
  springDatasourceDb: "hawkbit"
  # if springDatasourceUrl is set override default mysql db url
  springDatasourceUrl: ""
  springRabbitmqHost: "hawkbit-rabbitmq"
  springRabbitmqUsername: "hawkbit"
  springRabbitmqPassword: "hawkbit"

# optional env vars
extraEnv: {}
  # JAVA_TOOL_OPTIONS: "-Xms1024m -Xmx1024m"

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 500m
  #  memory: 1536Mi
  # requests:
  #  cpu: 100m
  #  memory: 1024Mi

nodeSelector: {}

tolerations: []

affinity: {}

podTemplate:
  annotations: {}

extraVolumes: []
extraVolumeMounts: []

configMap:
  mountPath: "/opt/hawkbit/config"

spring:
  profiles: "mysql"

config:
  application:
    server:
      useForwardHeaders: true
    hawkbit:
      ## Configuration for the device management federation
      ## ref: https://www.eclipse.org/hawkbit/apis/dmf_api/
      ## These configuration will become available once https://github.com/eclipse/hawkbit/pull/890 is merged
      # dmf:
      #   hono:
      #     enabled: false
      #     tenant-list-uri: "http://[DEVICE_REGISTRY_HOST]:8080/admin/tenants"
      #     device-list-uri: "http://[DEVICE_REGISTRY_HOST]:8080/admin/$$tenantId/devices"
      #     credentials-list-uri: "http://[DEVICE_REGISTRY_HOST]:8080/v1/credentials/$$tenantId/$$deviceId"
      #     authentication-method: "oidc"
      #     username: "[KEYCLOAK_HAWKBIT_USERNAME]"
      #     oidc-token-uri: "http://[KEYCLOAK_HOST]:8080/auth/realms/master/protocol/openid-connect/token"
      #     oidc-client-id: "[KEYCLOAK_DEVICE_REGISTRY_CLIENT_ID]"
    spring:
      cloud:
        stream:
          bindings:
            default:
              group: "hawkbit"
            device-created:
              destination: "device-registry.device-created"
            device-updated:
              destination: "device-registry.device-updated"
            device-deleted:
              destination: "device-registry.device-deleted"
      security:
        user:
          name: admin
  secrets:
    hawkbit:
      dmf:
        hono:
          password: "[KEYCLOAK_HAWKBIT_USER_PASSWORD]"
    spring:
      security:
        user:
          # the "{noop}" prefix is needed!
          password: "{noop}admin"
      datasource:
        username: hawkbit
        password: hawkbit


## dependency charts config
## ref: https://github.com/bitnami/charts/blob/master/bitnami/mysql/values.yaml
mysql:
  enabled: true
  primary:
    persistence:
      enabled: true
  volumePermissions:
    enabled: true
  architecture: standalone
  auth:
    username: hawkbit
    password: hawkbit
    database: hawkbit
  metrics:
    enabled: true

## ref: https://github.com/bitnami/charts/blob/master/bitnami/rabbitmq/values.yaml
rabbitmq:
  enabled: true
  persistence:
    enabled: true
  volumePermissions:
    enabled: true
  auth:
    username: hawkbit
    password: hawkbit
  metrics:
    enabled: true
