{{- $args := dict "dot" . "name" "service-command-router" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  {{- include "hono.metadata" $args | nindent 2 }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "watch"]
