{{- if .Values.adapters.lora.enabled }}
#
# Copyright (c) 2019, 2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
#
apiVersion: v1
kind: Service
metadata:
  {{- $args := dict "dot" . "component" "adapter-lora" "name" "adapter-lora" }}
  {{- include "hono.metadata" $args | nindent 2 }}
  {{- with .Values.adapters.lora.svc.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
  {{- if ( eq .Values.adapters.lora.hono.lora.insecurePortEnabled true ) }}
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
    {{- $httpArgs := dict "dot" . "port" 32080 }}
    {{- include "hono.nodePort" $httpArgs | nindent 4 }}
  {{- end }}
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
    {{- $httpsArgs := dict "dot" . "port" 32443 }}
    {{- include "hono.nodePort" $httpsArgs | nindent 4 }}
  selector:
    {{- include "hono.matchLabels" $args | nindent 4 }}
  {{- include "hono.serviceType" . }}
{{- with .Values.adapters.lora.svc.loadBalancerIP }}
  loadBalancerIP: {{ . | quote }}
{{- end }}
{{- end }}
