{{- if .Values.adapters.amqp.enabled }}
#
# Copyright (c) 2019, 2020 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
#
{{- $args := dict "dot" . "component" "adapter-amqp-vertx" "name" "adapter-amqp-vertx-conf" }}
apiVersion: v1
kind: Secret
metadata:
  {{- include "hono.metadata" $args | nindent 2 }}
type: Opaque
stringData:
  application.yml: |
    hono:
      app:
        maxInstances: {{ .Values.adapters.amqp.hono.app.maxInstances }}
      amqp:
        {{- if .Values.adapters.amqp.hono.amqp }}
        {{- .Values.adapters.amqp.hono.amqp | toYaml | nindent 8 }}
        {{- else }}
        bindAddress: "0.0.0.0"
        keyPath: "/etc/hono/key.pem"
        certPath: "/etc/hono/cert.pem"
        insecurePortEnabled: true
        insecurePortBindAddress: "0.0.0.0"
        tenantIdleTimeout: {{ .Values.adapters.defaultTenantIdleTimeout | quote }}
        {{- end }}
      {{- include "hono.healthServerConfig" .Values.adapters.amqp.hono.healthCheck | nindent 6 }}
      {{- include "hono.serviceClientConfig" $args | nindent 6 }}
    {{- include "hono.quarkusConfig" $args | indent 4 }}
data:
  key.pem: {{ .Files.Get "example/certs/amqp-adapter-key.pem" | b64enc }}
  cert.pem: {{ .Files.Get "example/certs/amqp-adapter-cert.pem" | b64enc }}
  trusted-certs.pem: {{ .Files.Get "example/certs/trusted-certs.pem" | b64enc }}
  adapter.credentials: {{ .Files.Get "example/amqp-adapter.credentials" | b64enc }}
{{- end }}